FROM potato-base
COPY index.html /app/gui/index.html
COPY chat.sh /app/bin/chat.sh
COPY bench.sh /app/bin/bench.sh
COPY echo.sh /app/bin/echo.sh
RUN chmod +x /app/bin/chat.sh /app/bin/bench.sh /app/bin/echo.sh
